FROM jam1024/nginx-python

# certbot
WORKDIR /opt/certbot

COPY ./certbot/CHANGELOG.md ./certbot/README.rst ./certbot/setup.py src/
COPY ./certbot/letsencrypt-auto-source/pieces/dependency-requirements.txt .
COPY ./certbot/acme src/acme
COPY ./certbot/certbot src/certbot

RUN apk add --no-cache --virtual .certbot-deps \
        libffi \
        libssl1.1 \
        openssl \
        ca-certificates \
        binutils
RUN apk add --no-cache --virtual .build-deps \
        gcc \
        linux-headers \
        openssl-dev \
        musl-dev \
        libffi-dev \
    && pip install -r /opt/certbot/dependency-requirements.txt \
    && pip install --no-cache-dir \
        --editable /opt/certbot/src/acme \
        --editable /opt/certbot/src \
    && apk del .build-deps

EXPOSE 80 443